### ISSUE TITLE
Reports wrong macOS version

### ISSUE THREAD

**Issue by frspp** [systemed/potlatch3#4]
Hi!

I'm downloaded Potlatch today and run it own macOS 11.1. Upon saving Potlatch says OS = macos 10.16.
<img width="587" alt="potlatch macos10-11 2020-12-31 at 12 06 44" src="https://user-images.githubusercontent.com/22942340/103405818-233c5700-4b61-11eb-9df7-9a4087a336f1.png">

**Comment by systemed** [comment]
That's fun! Apparently macOS now internally identifies itself as either 10.16.0 or 11.0 depending on how you build the app. It's not clear whether this is an AIR issue or because I'm doing the build on Mojave (10.14), but in either case it's not really something within my control to fix - Potlatch just uses `Capabilities.os` and faithfully reports whatever it sees there.
