### ISSUE TITLE
Does Potlatch3 distort tracks uploaded to OSM?

### ISSUE THREAD

**Issue by tracker51** [systemed/potlatch3#40]
Since a few weeks I use a new GNSS device for recording my tracks (10 measurement per second).  These tracks are astonishing precise because they are real-time corrected by SAPOS data.

The more disappointing is how the uploaded to OSM tracks are shown by Potlatch: totally distorted:

![image](https://github.com/systemed/potlatch3/assets/43145090/5b3be387-6494-48c1-bf4e-01e46277d830)

How come? What am I doing wrong? Any help is really appreciated.

Best regards

tracker51

**Comment by systemed** [comment]
Can you point to one of your tracks as uploaded to OSM (ideally set to public)?

**Comment by tracker51** [comment]
Hello Richard,

Many thanks for your lightning fast answer.

I am enclosing the tracks in question; additionally, you can find
them under the following denomonations:

https://www.openstreetmap.org/user/tracker51/traces/7496554
https://www.openstreetmap.org/user/tracker51/traces/7496418
https://www.openstreetmap.org/user/tracker51/traces/7457437

Best regards

Reinhard


Richard Fairhurst schrieb:

**Comment by systemed** [comment]
Ah, I think I see.

A few years ago a change was made to the OSM API relating to unordered GPS traces. https://github.com/openstreetmap/openstreetmap-website/issues/2046

If you upload a track as "public (shown in trace list and as anonymous, unordered points)", i.e. without timestamps, then the OSM API doesn't guarantee the ordering. As a result, in order to show a trace, P3 has to retrofit a likely ordering. This will potentially break things in the way you illustrate.

I think there are two ways you can avoid this:

- Upload your traces as "Trackable" or "Identifiable". This means P3 can use the ordering from the file you upload.
- Manually load your GPX files into P3, so you're not reliant on the behaviour of the OSM API. P3 will then trust the ordering in the file. You can do this with "Background" -> "Vector file" -> "File: Open..." (choose GPX).

**Comment by tracker51** [comment]
Hello Richard,

Many thanks! 

Best regards

tracker51
