### ISSUE TITLE
close changeset with "Save"

### ISSUE THREAD

**Issue by hakuchi** [systemed/potlatch3#9]
Potlach should close the changeset after pressing "Save".
This prevent user from having to large changesets or changesets over the entire world.

Mappers not always think abbout pressing "C" before opening/editing something other.

**Comment by jonpsp** [comment]
I disagree. Potlatch always encouraged regular saving as it was unable to
deal with editing something that someone else edited while the changeset
was open. I find the way that iD closes the changeset on every save quite
confusing.

I save quite regularly and this would mean I would create 10s-100s of
changesets for the same session, but all those changesets would be
logically connected with the same changeset comments.

Jon

**Comment by systemed** [comment]
I'll consider adding a checkbox to the Save dialogue that closes the changeset after saving (such that the checkbox persists with every save) if that's the user's choice.

I don't want to automatically close every changeset on save. Regular saving is to be encouraged because, as @jonpsp points out, it reduces the opportunity for editing conflicts, and just as crucially it reduces the risk of losing work from a program crash. Potlatch has for a long time warned you if you go more than 20 minutes without saving.

**Comment by hakuchi** [comment]
A checkbox where every user can decide if he will use "save and close" or "save only" sounds the perfect solution.

So if I edit something where I need more time I can use "save only" and if I go to fix error reports I can easy switch to "save and close"

**Comment by systemed** [comment]
P3 now has a "Close changeset" checkbox in the Save dialogue which, if selected, will automatically close after saving. This is persisted between changesets and editing sessions.

In addition, there's now a warning if you try to save into an existing changeset such that it would create a massive bbox (because I keep doing that...).

The Mac, AIR and Windows downloads are all updated.
